######################################################################
# Automatically generated by qmake (3.1) Mon Nov 20 08:20:42 2023
######################################################################
TEMPLATE = app
CONFIG += c++17
QT += core gui widgets
LIBS += -lpthread
LIBS += -lnsl -lresolv
QT += network

SOURCES += main.cpp \
           mainwindow.cpp

HEADERS += mainwindow.h
# Directories
